# Aptfile for hello-world

[aptfile]
# Main Aptfile data.
target = 1.0
# Required Ubuntu version.
ubuntu_req = 22.10
# Required Debian version (codename.)
debian_req = "bookworm"

[humanfriendly.info]
# This is designed to be read by appstores. Without it, you should NOT list your app on Linux
# app stores, and you should NOT recommend your app to non-developers. It's called "humanfriendly"
# because plain "package names" are made for experienced users and even "robots".

# Don't copy your package name if it's a codename (e.g. Debian package "nautilus" --> Display name "Files")
name = "Hello World"
description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
version = "1.0"

[apt.dependencies]
# Python3 dependency without specific version.
"python3" = ""
# gtkpool dependency with specific version.
# ON UBUNTU THIS PACKAGE IS IN UNIVERSE. For old versions not available on
# the system repos the Aptfile repository is used.
"gtkpool" = "0.5.0-9build2"
# Grub-Customizer dependency with URL.
# THIS PACKAGE DOES NOT EXIST ON THE UBUNTU REPOSITORY.
"https://launchpad.net/~danielrichter2007/+archive/ubuntu/grub-customizer/+files/grub-customizer_5.2.3-0ubuntu1~ppa1k_amd64.deb" = ""
